site_name: httpbin-wrapper
nav:
    - Introduction: index.md
    - Topics: topics.md
    - Prepare: prepare.md
    - Hands-on: 
        nodejs: nodejs.md
        java: java.md
        swift: swift.md
        python: python.md
        php: php.md
        go: go.md
        loopback: loopback.md
    - About: about.md
# theme: readthedocs
theme:
  name: 'material'