site_name: httpbin-wrapper
nav:
    - Introduction: index.md
    - Topics: topics.md
    - Prepare: prepare.md
    - Hands-on: 
        go: go.md
        # java (Liberty): java.md
        # java (spring): spring.md
        loopback: loopback.md
        nodejs: nodejs.md
        # php: php.md
        python flask: python.md
        # swift: swift.md
    - Deploy a OKD 3.11 in centos: okd.md
    - Deploy K3S in centos: k3s.md
    - About: about.md
# theme: readthedocs
theme:
  name: 'material'