site_name: httpbin-wrapper
nav:
    - Introduction: index.md
    - Topics: topics.md
    - Prepare: prepare.md
    - Hands-on: hands-on.md
    - About: about.md

# theme: readthedocs
theme:
  name: 'material'