apiVersion: v1
kind: Service
metadata:
  name: js-httpbin-service
  namespace: user01
spec:
  selector:
    app: js-httpbin-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-httpbin-deployment
  namespace: user01
  labels:
    app: js-httpbin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: js-httpbin-app
  template:
    metadata:
      labels:
        app: js-httpbin-app
    spec:
      containers:
      - name: js-httpbin-app
        image: mycluster.icp:8500/user01/js-nodeapp:1.0
        imagePullPolicy: Always
        # securityContext:
        #   privileged: false
        #   readOnlyRootFilesystem: true
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   capabilities:
        #     drop:
        #     - ALL
        livenessProbe:
          httpGet:
            path: /liveness
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5  
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: TARGET_URL
          value: https://httpbin.org
        - name: CONTAINER_PORT
          value: "3000"
        - name: TARGET_URI
          value: /delay/1
